import { LachesCharacter } from './laches-character.enum';
import { Turn } from './turn.interface';

export const LachesLamb: Turn<LachesCharacter>[] = [
  {
    character: LachesCharacter.Lysimachus,
    speech: [
      `You have seen the performance of the man fighting in armour, Nicias and Laches;`,
      `but my friend Melesias and I did not tell you at the time our reason for requesting you to come and see it with us.`,
      `However, we will tell you now; for we think we should speak our minds freely to friends like you.`,
      `Some people, of course, pour ridicule on such appeals, and when consulted for their advice will not say what they think, but something different, making the inquirer\'s wishes their aim, and speaking against their own judgement.`,
      `But you, we consider, not merely have the necessary discernment but will give us the benefit of it in telling us just what is in your minds;`,
      `and hence we have enlisted your counsel on the question which we are about to lay before you.`,
      `Now the matter about which I have made all this long preamble is this: we have two sons here,`,
      `my friend that one, called Thucydides after his grandfather,`,
      `and I this one; he also is named in the same way, after my father; we call him Aristeides.`,
      `Well, we have resolved to give them our most constant care, and not—as most fathers do when their boys begin to be young men -let them run loose as their fancy leads them,`,
      `but begin forthwith taking every possible care of them.`,
      `Now, knowing that you too have sons, we thought that you above all men must have concerned yourselves with the question of the kind of upbringing that would make the best of them;`,
      `and if by any chance you have not given your attention to the subject, we would remind you that it ought not to be neglected,`,
      `and we invite you to join us in arranging some way of taking care of our sons.\n`,
      `How we formed this resolve, Nicias and Laches, is worth hearing, even though the story be somewhat long.`,
      `My friend Melesias and I take our meals together, and our boys share our table.`,
      `Now, as I said at the beginning of my remarks, we are going to speak quite freely to you.`,
      `Each of us has many noble deeds of his own father to relate to these young fellows — their numerous achievements both in war and in peace,`,
      `when they were managing the affairs either of the allies or of this city;`,
      `but neither of us has any deeds of his own to tell.`,
      `We cannot help feeling ashamed that our boys should observe this, and we blame our fathers for leaving us to indulge ourselves when we began to be young men, while they looked after other folks\' affairs;`,
      `and we point the moral of it all to these young people,`,
      `telling them that if they are careless of themselves and will not take our advice they will win no reputation,`,
      `but if they take due pains they may very likely come to be worthy of the names they bear.`,
      `Now they, for their part, say they will do as we bid;`,
      `so we are now considering what lessons or pursuits will lead them to the highest attainable excellence.`,
      `Someone directed us to this particular accomplishment of fighting in armour, as being an admirable one for a young man to learn;`,
      `and he praised that man whose performance you were just watching, and then urged us to go and see him.`,
      `So we decided that it would be well to go and see the man ourselves, and to take you along with us not merely as companions at the show, but also as counsellors and co-partners, if you will be so good, in the matter of looking after our sons.`,
      `That is the question which we wanted to discuss with you.`,
      `And we look to you now, on your part, to give us your advice, first as to whether you think this accomplishment should be learnt or not,`,
      `and then as to any other such art or pursuit that you can recommend for a young man;`,
      `and also, how you feel inclined as regards our partnership.`,
    ],
  },
  {
    character: LachesCharacter.Nicias,
    speech: [
      `For myself, Lysimachus and Melesias, I highly approve of your purpose, and am ready to lend a hand;`,
      `and I may say the same, I think, for Laches here.`,
    ],
  },
  {
    character: LachesCharacter.Laches,
    speech: [
      `Yes, you think truly, Nicias.`,
      `For that remark which Lysimachus made just now about his father and the father of Melesias was very apposite, `,
      `in my opinion, not only to them but to us and to all who deal with public affairs: `,
      `it is practically the rule with them, as he says, to treat their private concerns, whether connected with children or anything else, in a slighting, careless spirit.`,
      `You are quite right in saying that, Lysimachus;`,
      `but to invite us to be your advisers for the education of your boys, and not to invite Socrates here, is to me very strange, `,
      `when, to begin with, he is of your district, `,
      `and then he is always spending his time wherever there is any such excellent study or pursuit for young men as you are seeking.`,
    ],
  },
]
